# Generated by Django 4.1.6 on 2023-02-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korzin', '0002_bet_color_history_shoe_size_delete_basket_shoe_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(max_length=100),
        ),
    ]
